name: .NET

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
        arch: [x64]
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x
          include-prerelease: false

      - name: Build
        run: dotnet build -c Release

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DevMan-3.22.zip
          path: bin/*
          if-no-files-found: error
          compression-level: 0
        
  release:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: upload artifacts
        run: gh release upload '3.22' DevMan-${{ matrix.arch }}-3.22.zip -R "${GITHUB_REPOSITORY}"
